set search_path = "data";
drop schema if exists data cascade;
create schema if not exists data;


drop table if exists data.towns cascade;
create table data.towns (
    towns_id int not null primary key generated by default as identity,
    towns_name text not null
);

drop table if exists data.museums cascade;
create table data.museums (
    museums_id int not null primary key generated by default as identity,
    museums_name text not null,
    street_name text not null,
    building_number int not null,
    towns_id int not null references data.towns(towns_id)
);

drop table if exists data.historical_monuments cascade;
create table data.historical_monuments (
    monuments_id int not null primary key generated by default as identity,
    monuments_name text not null,
    type_of_historical_monument text not null,
    date_of_entry text not null,
    street_name text not null,
    building_number int not null
);

drop table if exists data.immovable_monuments cascade;
create table data.immovable_monuments (
    monuments_id int not null primary key generated by default as identity, --zabytki nieruchome
    monuments_name text not null,
    architectural_style text not null,
    street_name text not null,
    building_number int not null
);


drop table if exists data.voivodeships cascade;
create table data.voivodeships (
    voivodeships_id int not null primary key generated by default as identity,
    voivodeships_name text not null
);

drop table if exists data.towns_voivodeships cascade;
create table data.towns_voivodeships (
    towns_id int references data.towns (towns_id),
    voivodeships_id int references data.voivodeships (voivodeships_id),
    primary key (towns_id, voivodeships_id)
);

drop table if exists data.towns_historical_monuments cascade;
create table data.towns_historical_monuments (
    towns_id int references data.towns (towns_id),
    monuments_id int references data.historical_monuments (monuments_id),
    primary key (towns_id, monuments_id)
);

drop table if exists data.towns_immovable_monuments cascade;
create table data.towns_immovable_monuments (
    towns_id int references data.towns (towns_id),
    monuments_id int references data.immovable_monuments (monuments_id),
    primary key (towns_id, monuments_id)
);